### ISSUE TITLE
bb url tags are wrapped twice in html a tags

### ISSUE THREAD

**Issue by boringvipper** [oprel/emanon#3]
## The post:

```
[url]http://a.b[/url]
```
## produces:

``` html
<a href="http://a.b"><a href="http://a.b">http://a.b</a></a>
```
## solution:

Do not auto detect links in a/url tags (both for the href and the innertext of the a tag). I noticed with your url auto detect regex that the beginning starts out with `(?<!href=")`. I don't really know what this is supposed to do. If it's supposed to make the expressions not capture urls prefixed by `<a href="`, wouldn't that make it `(?!<a href=")`? I just don't really understand the syntax I guess.

**Comment by oprel** [comment]
`(?<!href=")` is negatively looking backwards to make sure it doesn't replace the links that are actually the href of another link. I thought this behaviour was okay at first, because that way people have a harder time masking links as different links with the [url=] tag, but you're right, the HTML should be clean.

##### Here's the solution I found:

`my $urlpattern = qr{
        $protocol
        [a-z0-9-]+
        (?:\.[a-z0-9-]+)+
        (?::[0-9]{4})?
        (?:(?!<).)*
        (?:[/?](?:[\x21-\x25\x27-\x5A\x5E-\x7E]|&amp;)+)?
    }x;`

Here `(?:(?!<).)*` looks forward for any <'s, but it only works in the regex debuggers I've tried not in the actual codebase. Any ideas?

**Comment by oprel** [comment]
The solution was much simpler; don't know why I didn't think of it earlier. This just strips all anchor tags from the [url] content:

`$content =~ s/<a.*?>|<\/a>//g;`

I moved the link detection lines back to the top where they belong.

**Comment by boringvipper** [comment]
Sorry for the late response. Haven't really been checking this github account. But awesome job anyways!
